[config]
output-size = 1000

[[cover]]
playlist-name = "Yamaoka Work"
bg-image = "sh-office.jpg"
colour-gradient = "blue"

[[cover]]
playlist-name = "Triage"
bg-image = "cd-pile.jpg"

[[cover]]
playlist-name = "\u1F44D"
bg-image = "gpm.png"
bg-colour = "white"
colour-gradient = "orange"  
scale = 50
position = "center"
use-white-logo = true