[config]
output-size = 1000

[[cover]]
main-text = "Yamaoka Work"
bg-image = "sh-office.jpg"

[[cover]]
main-text = "Triage"
bg-image = "cd-pile.jpg"
colour-gradient = "dull"
use-white-logo = true
do-not-greyscale = true
font-colour = "black"

[[cover]]
main-text = "Thumbs Up"
bg-image = "gpm.png"
bg-colour = "white"
colour-gradient = "orange_coral"
scale = 50
position = "bottom"
use-white-logo = true